<?php
    use Zend\Session\Container;
    $sessionLogin = new Container('credo');
    $qtyId = $result['qty_id'];
    // \Zend\Debug\Debug::dump($result);die;
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Qty Details</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <a href="<?php echo $this->url('admin-qty', array('action' => 'index')); ?>">
                        <li class="breadcrumb-item">Qty Details</li>
                    </a>
                    <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Modify</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="content">
        <div class="block block-rounded block-bordered">
            <div class="block-header block-header-default">
                <h3 class="block-title">Modify Qty Details</h3>
            </div>
            <div class="block-content">
                <form name="qtyInformation" id="qtyInformation" class="mb-5" action="<?php echo $this->url('admin-qty', array('action' => 'edit')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="name">Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['qty_name'];?>" class="form-control isRequired" id="name" name="name" placeholder="Enter the name" title="Please enter the name" onblur="checkNameValidation('qty_details', 'qty_name', this, '<?php echo "qty_id##" . $qtyId; ?>', 'Entered name exist . Please enter an another name.')">
                        </div>
                        <label class="col-sm-2 col-form-label" for="status">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="status" name="status" title="Please select the Zone status">
                                <option value="active" <?php echo (isset($result['qty_status']) && $result['qty_status'] == "active")?"selected='selected'":"";?>>Active</option>
                                <option value="inactive" <?php echo (isset($result['qty_status']) && $result['qty_status'] == "inactive")?"selected='selected'":"";?>>Inactive</option>
                            </select>
                        </div>
                    </div>
                    <hr>
                    <div class="row items-push submit">
                        <div class="col-lg-7 offset-lg-4">
                            <input type="hidden" id="qtyId" name="qtyId" value="<?php echo base64_encode($result['qty_id']);?>"/>
                            <a href="<?php echo $this->url('admin-qty', array('action' => 'index')); ?>" class="btn btn-hero-dark">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-hero-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'qtyInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('qtyInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: checkValue,
                fnct: fnct
            },
            function(data) {
                if (data > 0) {
                    alert(msg,'err');
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                } else {
                    duplicateName = true;
                }
            });
        }
    }
</script>