
<!-- CONTENT 
============================================= -->
<div class="content" style="text-align: center;border-top: 1px solid #00c8e6;padding-top:2%;">
	<div class="container layout" style="min-height:300px;">
			<!-- <h3><?php echo $this->translate('A 404 error occurred') ?></h3> -->
			<h1 style=" color: #00c8e682; ">A <span style=" font-size: 100px; color: #00c8e6; ">404</span> error occurred</h1>
			<h5>Sorry. We were unable to find the page or document you were looking for.</h5>
	</div>
</div>
<!-- END CONTENT 
============================================= -->
