<?php
    use Zend\Session\Container;
    $sessionLogin = new Container('credo');
    $productId = $result['id'];
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Product</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <a href="<?php echo $this->url('admin-product', array('action' => 'index')); ?>">
                        <li class="breadcrumb-item">Product</li>
                    </a>
                    <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Modify</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="content">
        <div class="block block-rounded block-bordered">
            <div class="block-header block-header-default">
                <h3 class="block-title">Modify Product Details</h3>
            </div>
            <div class="block-content">
                <form name="productInformation" id="productInformation" class="mb-5" action="<?php echo $this->url('admin-product', array('action' => 'edit')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="name">Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="name" name="name" placeholder="Enter the name" title="Please enter the name" onblur="checkNameValidation('product', 'name', this, '<?php echo "id##" . $productId; ?>', 'Entered name exist . Please enter an another name.')">
                        </div>
                        <label class="col-sm-2 col-form-label" for="slug">Slug<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="slug" name="slug" placeholder="Enter the slug" title="Please enter the slug" onblur="checkNameValidation('product', 'slug', this, '<?php echo "id##" . $productId; ?>', 'Entered slug exist . Please enter an another slug.')">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="parentId">Category<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control selectpicker isBootstrapSelect isRequired" data-selected-text-format="count > 3" data-live-search="true" data-container="body" data-actions-box="true" id="parentId" name="parentId" data-placeholder="Choose one parent category ..." title="Please select the parent category">
                                <?php if(isset($categorylist) && count($categorylist) > 0){
                                    foreach($categorylist as $category){
                                        echo '<option value="'.base64_encode($category['category_id']).'">'.$category['category_name'].'</option>';
                                    }
                                }?>
                            </select>
                        </div>
                        <label class="col-sm-2 col-form-label" for="description">Description</label>
                        <div class="col-sm-4">
                            <textarea type="text" class="form-control" id="description" name="description" placeholder="Enter the description" title="Please enter the description"></textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="name">HSN</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="han" name="han" placeholder="Enter the hsn" title="Please enter the hsn" onblur="checkNameValidation('product', 'hsn', this, '<?php echo "id##" . $productId; ?>', 'Entered hsn was already exist . Please enter an another hsn.')">
                        </div>
                        <label class="col-sm-2 col-form-label" for="name">SKU</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="sku" name="sku" placeholder="Enter the sku" title="Please enter the sku" onblur="checkNameValidation('product', 'sku', this, '<?php echo "id##" . $productId; ?>', 'Entered sku was already exist . Please enter an another sku.')">
                        </div>
                        <label class="col-sm-2 col-form-label" for="status">Status<span class="mandatory">*</span></label>
                    </div>
                    <hr>
                    <div class="form-group row">
                        <h4>Options</h4>
                        <label class="col-sm-2 col-form-label" for="optColour">Colour</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="optColour" name="optColour" placeholder="Enter the colour of the product" title="Please enter the colour of the product">
                        </div>
                        <label class="col-sm-2 col-form-label" for="optGrade">Grade<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="optGrade" name="optGrade" title="Please select the grade">
                                <option value="sn">SN</option>
                                <option value="sm">SM</option>
                                <option value="sl">SL</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="optType">Type<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="optType" name="optType" title="Please select the type of the product">
                                <option value="two-wheeler">Two Wheeler</option>
                                <option value="three-wheeler">Three Wheeler</option>
                                <option value="four-wheeler">Four Wheeler</option>
                                <option value="heavy-transport">Heavy Transport</option>
                            </select>
                        </div>
                        <label class="col-sm-2 col-form-label" for="remainderQty">Reminder Quantity</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="remainderQty" name="remainderQty" placeholder="Enter the reminder quantity" title="Please enter the reminder quantity">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="status">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="status" name="status" title="Please select the Zone status">
                                <option value="active">Active</option>
                                <option value="inactive">Inactive</option>
                            </select>
                        </div>
                    </div>
                    <hr>
                    <div class="row items-push submit">
                        <div class="col-lg-7 offset-lg-4">
                            <input type="hidden" id="productId" name="productId" value="<?php echo base64_encode($result['id']);?>"/>
                            <a href="<?php echo $this->url('admin-product', array('action' => 'index')); ?>" class="btn btn-hero-dark">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-hero-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    $(document).ready(function(){
		$("#name").stringToSlug({
			getPut : "#slug"
		});
	});
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'productInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('productInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: checkValue,
                fnct: fnct
            },
            function(data) {
                if (data > 0) {
                    alert(msg,'err');
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                } else {
                    duplicateName = true;
                }
            });
        }
    }
</script>