<?php

use Zend\Session\Container;

$sessionLogin = new Container('user');
$role = $sessionLogin->roleCode;

$acl = $this->layout()->acl;
if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\Zone', 'edit')) {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
} else {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<style>
.jcr,.jpr {
    border-radius: 10px;
}
.filter-class {
    border: 1px solid #e2e0e0;
    padding: 10px;
    margin: 10px;
}

.filter-class-heading {
    margin-top: -20px;
    background: white;
    width: fit-content;
    padding: 0px 10px;
    color: gray;
}

.h3,
h3 {
    font-size: 1.0rem;
}

td.center.inline {
    /* display: -webkit-inline-box; */
    text-align: center;
}

.custom-control.custom-switch {
    padding-top: 7px;
}
thead th:last-child,
tbody td:last-child {
    position: sticky;
    right: 0px;
    z-index: 1;
    background: white;
}
table.dataTable tr th.select-checkbox.selected::after {
    content: "✔";
    margin-top: -11px;
    margin-left: -4px;
    text-align: center;
    text-shadow: rgb(176, 190, 217) 1px 1px, rgb(176, 190, 217) -1px -1px, rgb(176, 190, 217) 1px -1px, rgb(176, 190, 217) -1px 1px;
}
</style>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Product</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <?php if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\Product', 'add')) {?>
                        <a href="javascript:void(0);" onclick="showAddForm(this,'add-btn');" class="btn btn-hero-primary pull-right add-btn" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add New Product</a>
                        <?php }?>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="content show-form" style="display: none;">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add Product Details</h3>
        </div>
        <div class="block-content">
            <form name="productInformation" id="productInformation" class="mb-5" action="<?php echo $this->url('admin-product', array('action' => 'add')); ?>" method="post">
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="name">Name<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control isRequired" id="name" name="name" placeholder="Enter the name" title="Please enter the name" onblur="checkNameValidation('product', 'name', this, null, 'Entered name id exist . Please enter an another name.')">
                    </div>
                    <label class="col-sm-2 col-form-label" for="slug">Slug<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control isRequired" id="slug" name="slug" placeholder="Enter the slug" title="Please enter the slug" onblur="checkNameValidation('product', 'slug', this, null, 'Entered slug id exist . Please enter an another slug.')">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="categoryId">Category<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control selectpicker isBootstrapSelect isRequired" data-selected-text-format="count > 3" data-live-search="true" data-container="body" data-actions-box="true" id="categoryId" name="categoryId" data-placeholder="Choose one category ..." title="Please select the category">
                            <?php if(isset($categorylist) && count($categorylist) > 0){
                                foreach($categorylist as $category){
                                    echo '<option value="'.base64_encode($category['category_id']).'">'.$category['category_name'].'</option>';
                                }
                            }?>
                        </select>
                    </div>
                    <label class="col-sm-2 col-form-label" for="description">Description</label>
                    <div class="col-sm-4">
                        <textarea type="text" class="form-control" id="description" name="description" placeholder="Enter the description" title="Please enter the description"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="hsn">HSN</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="hsn" name="hsn" placeholder="Enter the hsn" title="Please enter the hsn" onblur="checkNameValidation('product', 'hsn', this, null, 'Entered hsn was already exist . Please enter an another hsn.')">
                    </div>
                    <label class="col-sm-2 col-form-label" for="name">SKU</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="sku" name="sku" placeholder="Enter the sku" title="Please enter the sku" onblur="checkNameValidation('product', 'sku', this, null, 'Entered sku was already exist . Please enter an another sku.')">
                    </div>
                </div>
                <hr>
                <h4>Price</h4>
                <hr>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="purchasePrice">Purchase Price</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="purchasePrice" name="purchasePrice" placeholder="Enter the purchase price" title="Please enter the purchase price">
                    </div>
                    <label class="col-sm-2 col-form-label" for="dealerPrice">Dealer Price</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="dealerPrice" name="dealerPrice" placeholder="Enter the dealer price" title="Please enter the dealer price">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="mrpPrice">MRP Price</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="mrpPrice" name="mrpPrice" placeholder="Enter the mrp price" title="Please enter the mrp price">
                    </div>
                    <label class="col-sm-2 col-form-label" for="tax">TAX</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="tax" name="tax" placeholder="Enter the tax" title="Please enter the tax">
                    </div>
                </div>
                <hr>
                <h4>Options</h4>
                <hr>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="optColour">Colour</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="optColour" name="optColour" placeholder="Enter the colour of the product" title="Please enter the colour of the product">
                    </div>
                    <label class="col-sm-2 col-form-label" for="optGrade">Grade<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control isRequired" id="optGrade" name="optGrade" title="Please select the grade">
                            <option value="sn">SN</option>
                            <option value="sm">SM</option>
                            <option value="sl">SL</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="optType">Type<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control isRequired" id="optType" name="optType" title="Please select the type of the product">
                            <option value="two-wheeler">Two Wheeler</option>
                            <option value="three-wheeler">Three Wheeler</option>
                            <option value="four-wheeler">Four Wheeler</option>
                            <option value="heavy-transport">Heavy Transport</option>
                        </select>
                    </div>
                    <label class="col-sm-2 col-form-label" for="remainderQty">Reminder Quantity</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="remainderQty" name="remainderQty" placeholder="Enter the reminder quantity" title="Please enter the reminder quantity">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="productQtyMap">Qty's<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control isRequired selectpicker isBootstrapSelect" multiple data-selected-text-format="count > 3" data-live-search="true" data-container="body" data-actions-box="true" id="productQtyMap" name="productQtyMap[]" title="Select the multiple qty's">
                            <?php if(isset($qtylist) && count($qtylist) > 0){
                                foreach($qtylist as $qty){
                                    echo '<option value="'.base64_encode($qty['qty_id']).'">'.ucwords($qty['qty_name']).'</option>';
                                }
                            }?>
                        </select>
                    </div>
                    <label class="col-sm-2 col-form-label" for="status">Status<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control isRequired" id="status" name="status" title="Please select the Zone status">
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </div>
                </div>
                <hr>
                <div class="row items-push submit">
                    <div class="col-lg-7 offset-lg-4">
                        <a href="javascript:void(0);"  onclick="showAddForm(this,'cancel-btn');" class="btn btn-hero-dark">Cancel</a>&nbsp;
                        <button type="submit" class="btn btn-hero-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
        </div>
        <div class="block-content block-content-full table-responsive">
            <table id="qtyTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Grade</th>
                        <th>Description</th>
                        <th>Status</th>
                        <?php if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\Product', 'edit')) { ?>
                        <th>Action</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="6" class="dataTables_empty" align="center">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'productInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('productInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: checkValue,
                fnct: fnct
            },
            function(data) {
                if (data > 0) {
                    alert(msg,'err');
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                } else {
                    duplicateName = true;
                }
            });
        }
    }
    $(document).ready(function() {
        $("#name").stringToSlug({
			getPut : "#slug"
        });
        
        oTable = $('#qtyTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "stateSave": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "sAjaxSource": "<?php echo $this->url('admin-product', array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    });
    
    function changeStatus(catId,catStatus){
        $.blockUI();
        $.post("<?php echo $this->url('admin-product', array('action' => 'change-status')); ?>", {id: catId, status : catStatus},
        function(data) {
            oTable.fnDraw();
            $.unblockUI();
        });
        afterCallback();
    }

    function showAddForm(obj,btn){
        if(btn == 'add-btn'){
            $(obj).hide(500);
            $('.show-form').show(500);
        }else{
            $('.show-form').hide(500);
            $('.add-btn').show(500);
        }
    }
</script>