<!--================Breadcrumb Area =================-->
<section class="breadcrumb_area br_image">
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle">Register Event</h2>
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active">Register Event</li>
            </ol>
        </div>
    </div>
</section>
<!--================Breadcrumb Area =================-->

<!-- ============== For registering the form ========= -->
<div class="section-top-border">
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <h3 class="mb-30 title_color">Form Element</h3>
            <form action="#">
                <div class="mt-10">
                    <input type="text" name="first_name" placeholder="First Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'First Name'" required class="single-input">
                </div>
            </form>
        </div>
    </div>
</div>